---
- name: Install package
  apt:
    name: isc-dhcp-server
    name: vlan
- name: Add the 802.1q module
  modprobe:
    name: 8021q
    state: present
  - name: add line 8021q to /etc/modules
  lineinfile:
    path: /etc/modules
    regexp: '^8021q'
    line: 8021q
- name: Insert/Update vlan in /etc/network/interfaces
  template:
    src: templates/templates_etc-network-interface.j2
    dest: /etc/network/interfaces
  notify:
    - restart_isc_dhcp_server
- name: Update vlan in /etc/default/isc-dhcp-server
  template:
    src: templates/templates_etc-dhcp-dhcpd.j2
    dest: /etc/default/isc-dhcp-server
  notify:
    - restart_isc_dhcp_server
- name: Update vlan in /etc/dhcpcd.conf
  template:
    src: templates/templates_etc-dhcpcd.j2
    dest: /etc/dhcpcd.conf
  notify:
    - restart_isc_dhcp_server
- name: Update subnet in /etc/dhcp/dhcpd.conf
  template:
    src: templates/templates_etc-subnet.j2
    dest: /etc/dhcp/dhcpd.conf
  notify:
    - restart_isc_dhcp_server
- name: Enable service isc-dhcp-server
  service:
    name: isc-dhcp-server
    enabled: yes
- name: Start Service isc-dhcp-server
  service:
    name: isc-dhcp-server
    state: started